name: tic_tac_toe_v2
description: A simple mobile game for playing Tic Tac Toe with a friend or with an AI.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  animated_icon: ^0.0.9
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/tic_tac_toe.png

flutter_native_splash:
  android: true
  ios: true
  web: false
  image: "assets/images/tic_tac_toe.png"
  color: "#FFFFFF"
  android_12: null

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/tic_tac_toe.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/tic_tac_toe.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/tic_tac_toe.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/tic_tac_toe.png"
