// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM0B_KrfqwzYx7tb45HFpubEoVwBKbh9A',
    appId: '1:446098444143:web:0f67e328b378005ca8629a',
    messagingSenderId: '446098444143',
    projectId: 'tic-tac-toe-c5kkpo',
    authDomain: 'tic-tac-toe-c5kkpo.firebaseapp.com',
    storageBucket: 'tic-tac-toe-c5kkpo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA82dUh15W5EBmvS_3SwbPfTt4d3N31Iqk',
    appId: '1:446098444143:android:2410bb755761b5aea8629a',
    messagingSenderId: '446098444143',
    projectId: 'tic-tac-toe-c5kkpo',
    storageBucket: 'tic-tac-toe-c5kkpo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJUR_WxI_ctku5YifClgF8OzLmHytlN4I',
    appId: '1:446098444143:ios:4fa68302e2975e97a8629a',
    messagingSenderId: '446098444143',
    projectId: 'tic-tac-toe-c5kkpo',
    storageBucket: 'tic-tac-toe-c5kkpo.appspot.com',
    iosClientId: '446098444143-s7olu3ooqpcbl6v0dd6c3scmscku3c6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticTacToeV2',
  );
}
